server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ${SERVER_ERROR_INCLUDE_STACKTRACE:never}

security:
  ignored:
    - "*.bundle.*"

spring:
  application:
    name: protreky
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC